### ISSUE TITLE
Menu does not work on autotuneresults.html when menu is collapsed

### ISSUE THREAD

**Issue by VArcht** [d-ronin/d-ronin.github.io#14]
The menu button does not work when in "mobile" mode

**Comment by VArcht** [comment]
@chasd00  maybe you could look into it?

**Comment by chasd00** [comment]
something like this? http://codepen.io/SitePoint/pen/uIemr

**Comment by chasd00** [comment]
Nevermind, I see the issue. Will try to get a fix in tonight.

**Comment by mlyle** [comment]
Fixed by #15
