### ISSUE TITLE
Copying links to doc pages sucks

### ISSUE THREAD

**Issue by mlyle** [d-ronin/d-ronin.github.io#49]
1. When you go to a section, the #anchor-part-of-url isn't on the end in the progress bar; so it's hard to cite things on IRC.
2. readme.io also gave you a little anchor icon when you floated next to a link to get that anchor uri; would be nice for us to get that, too.

**Comment by tracernz** [comment]
Oh yep. Should be doable I think? Also would be nice to have a clipboard button next to the commands etc.
