### ISSUE TITLE
Cannot Close Tune popup in IE after clicking detail link

### ISSUE THREAD

**Issue by VArcht** [d-ronin/d-ronin.github.io#7]
Need to see if the CORS issue can be handled or just open link in a new tab

**Comment by chasd00** [comment]
I'm working on a re-styling of the autotune page. I'll have a pull request in a couple days, it should address this issue

**Comment by chasd00** [comment]
With the new autotune page this issue can be re-tested and likely closed

**Comment by VArcht** [comment]
Related. Dustin added CORS handling on the server a while back. I should have revisited this then.

BTW, did you see that the popups are not working? Some issue with remodal().

**Comment by chasd00** [comment]
So it looks like the application-d2500355.js which is what I included to make the menu work is just jquery+sizzle (I copy/pasted from index). When I included that script at the bottom of autotuneresults.html it killed the DataTable and remodal plugin loaded prior in <head>. What I'll do is replace the jquery include in <head> with application-d2500355.js

Pull request coming shortly, so this is two bugs with my simple autotune page, so much for first impressions..
